import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';
import js from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

const nextConfigs = compat.extends('next/core-web-vitals', 'next/typescript', '@tata-v/eslint-config-react-base');

const config = [
  // ...compat.extends(
  //   'next/core-web-vitals',
  //   'next/typescript',
  // '@tata-v/eslint-config-react-base',
  // 'eslint:recommended',
  // 'plugin:react/recommended',
  // 'plugin:@typescript-eslint/recommended',
  // 'plugin:react-hooks/recommended'
  // ),
  ...nextConfigs,
  {
    ignores: ['.next/*', 'node_modules', '**/.env*'],
    files: ['**/*.{js,mjs,cjs,ts,jsx,tsx}'],
    plugins: { '@stylistic': stylistic },
    rules: {
      '@stylistic/indent': ['error', 2, { SwitchCase: 1 }],
      'react/jsx-indent': 'off',
      'react/jsx-indent-props': 'off',
      'react/prop-types': 'off',
      'no-restricted-imports': 'off',
      '@next/next/no-title-in-document-head': 'off',
      'no-empty': 'off',
      'no-unused-vars': 'off',
      'no-restricted-syntax': 'off',
      'no-prototype-builtins': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/naming-convention': 'off',
      'default-case': 'off',
      '@typescript-eslint/no-shadow': 'off',
      'no-restricted-globals': 'off',
      'no-mixed-operators': 'off',
      'no-underscore-dangle': 'off',
      '@next/next/no-img-element': 'off',
      'space-infix-ops': ['error', { int32Hint: false }],
      'react/no-danger': 'off',
      'no-dupe-keys': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      'import/no-named-as-default': 'off',
      'arrow-body-style': 'off',
      'no-unused-disable': 'off',
      'react/react-in-jsx-scope': 'off',
      'react-hooks/exhaustive-deps': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      'jsx-a11y/alt-text': 'off',
      'react/display-name': 'off',
      'react/no-unused-prop-types': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-wrapper-object-types': 'off',
      'import/prefer-default-export': 'off',
      'no-debugger': 'off',
      'react/function-component-definition': [2, { namedComponents: ['arrow-function', 'function-declaration'] }],
      'import/no-unresolved': 'off',
      'react/jsx-props-no-spreading': 'off',
      'linebreak-style': 0,
      'import/extensions': 'off',
      'no-use-before-define': 0,
      'import/no-extraneous-dependencies': 0,
      'no-shadow': 0,
      'jsx-a11y/no-noninteractive-element-interactions': 0,
      'react/button-has-type': 'off',
      'no-alert': 'off',
      'max-len': 'off',
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
      'react/destructuring-assignment': 'off',
      'react/no-array-index-key': 'off',
      'no-param-reassign': 'off',
      'no-undef': 'off',
      'object-curly-newline': 'off',
      'react/jsx-no-useless-fragment': 'off',
      'jsx-a11y/control-has-associated-label': 'off',
      'react/require-default-props': 'off',
      'consistent-return': 'off',
      '@typescript-eslint/no-var-requires': 'off',
      'import/order': 'off',
      'no-tabs': 'off',
      'camelcase': 'off',
      'dot-notation': 'off',
      'no-redeclare': 'off',
      'prefer-destructuring': 'off',
      'no-unsafe-optional-chaining': 'off',
      'jsx-a11y/label-has-associated-control': 'off',
      'import/no-absolute-path': 'error',
      'func-names': 'off',
      'react/no-unknown-property': 'off',
      'no-multi-assign': 'off',
      '@typescript-eslint/no-use-before-define': 'off',
      'no-plusplus': 'off',
      'no-return-assign': 'off',
      'react-hooks/rules-of-hooks': 'off',
      'eol-last': 'off',
      'quote-props': 'off',
      'react/sort-comp': 'off',
      'class-methods-use-this': 'off',
      'react/jsx-no-constructed-context-values': 'off',
      'import/export': 'off',
      'import/named': 'off',
      'react/no-unstable-nested-components': 'off',
    },
  },
];

export default config;
