import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import RecoilProvider from 'src/components/provider/RecoilProvider';
import './globals.css';
import './iconfonts.css';
import './reset.css';
import StyledComponentsRegistry from 'src/components/provider/StyledComponentsRegistry';
import DefaultLayout from 'src/components/Layout/DefaultLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'AuraWave',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RecoilProvider>
      <StyledComponentsRegistry>
        <html lang="ko">
          <body className={inter.className}>
            <DefaultLayout>
              {children}
            </DefaultLayout>
            <Toaster />
          </body>
        </html>
      </StyledComponentsRegistry>
    </RecoilProvider>
  );
}
