import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import RecoilProvider from 'src/components/provider/RecoilProvider';
import './globals.css';
import './iconfonts.css';
import StyledComponentsRegistry from 'src/components/provider/StyledComponentsRegistry';
import DefaultLayout from 'src/components/Layout/DefaultLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RecoilProvider>
      <StyledComponentsRegistry>
        <html lang="en">
          <body className={inter.className}>
            <DefaultLayout>
              {children}
            </DefaultLayout>
          </body>
        </html>
      </StyledComponentsRegistry>
    </RecoilProvider>
  );
}
